### ISSUE TITLE
Optionally display password as stars

### ISSUE THREAD

**Issue by GameplayJDK** [devgeeks/Encryptr#151] opened 2015-03-21 08:13 UTC
I think it would be good to have a little checkbox/option to change the way passwords are shown. So we can switch between cleartext and stars (*).

**Comment by devgeeks** [comment] 2015-03-21 11:27
Something similar to that is coming in the next version. It should be out before the end of the month.

Duplicate of #102

**Closed by devgeeks** 2015-03-21 11:27 UTC
Labels: 3 - Done, duplicate, UI/UX

**Comment by GameplayJDK** [comment] 2015-03-21 13:16
Thanks, didn't see that one (#102) though I looked for it...
